version: '3.8'

services:
  # App service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doctor-consultation-app
    ports:
      - "6001:6000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=6000
    restart: unless-stopped

  # MongoDB service (for future use)
  # mongodb:
  #   image: mongo:7.0
  #   container_name: doctor-consultation-mongodb
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=admin
  #     - MONGO_INITDB_ROOT_PASSWORD=password123
  #     - MONGO_INITDB_DATABASE=doctor_consultation
  #   volumes:
  #     - mongodb_data:/data/db
  #   restart: unless-stopped

  # Redis service (for future caching/sessions)
  redis:
    image: redis:7-alpine
    container_name: doctor-consultation-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
